# .github/workflows/linting.yml
name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef6144
      - uses: ruby/setup-ruby@3ff19f5
        with:
          bundler-cache: true
      - run: bundle exec rubocop --parallel

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef6144
      - uses: ruby/setup-ruby@3ff19f5
        with:
          bundler-cache: true
      - run: bundle exec brakeman --no-pager -w1

  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef6144
      - uses: ruby/setup-ruby@3ff19f5
        with:
          bundler-cache: true
      - run: bundle exec bundle-audit check
